In [2]:
import torch

In [6]:
a = torch.rand(4,3,3)

In [7]:
a

tensor([[[0.5476, 0.6700, 0.9225],
         [0.7258, 0.5557, 0.7145],
         [0.1536, 0.2639, 0.1462]],

        [[0.4889, 0.7419, 0.6450],
         [0.1224, 0.2422, 0.5954],
         [0.1438, 0.7350, 0.8808]],

        [[0.5222, 0.9456, 0.9543],
         [0.9288, 0.4637, 0.6412],
         [0.1227, 0.3780, 0.9955]],

        [[0.4021, 0.7653, 0.3772],
         [0.5898, 0.7521, 0.6238],
         [0.1814, 0.9457, 0.8915]]])

In [11]:
2.71**(0.67)/(2.71**(0.5476)+2.71**(0.67)+2.71**(0.9225))


0.31532084052556336

In [3]:
device = torch.device("cuda")

In [13]:
a = torch.arange(1,21).reshape((2,2,5)).to(device)
a

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]],

        [[11, 12, 13, 14, 15],
         [16, 17, 18, 19, 20]]], device='cuda:0')

In [16]:
a.shape

torch.Size([2, 2, 5])

In [9]:
torch.softmax(a,dim = 2)

tensor([[[0.2789, 0.3153, 0.4058],
         [0.3531, 0.2978, 0.3491],
         [0.3216, 0.3591, 0.3192]],

        [[0.2893, 0.3726, 0.3381],
         [0.2680, 0.3021, 0.4300],
         [0.2043, 0.3689, 0.4268]],

        [[0.2458, 0.3754, 0.3787],
         [0.4205, 0.2641, 0.3154],
         [0.2135, 0.2756, 0.5110]],

        [[0.2930, 0.4213, 0.2858],
         [0.3114, 0.3663, 0.3222],
         [0.1930, 0.4144, 0.3926]]])

In [2]:
import numpy as np

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(a)

numpy.ndarray

In [7]:
b = np.array(a, dtype="float16").reshape(5,2)
b

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]], dtype=float16)

In [9]:
type(b.size)

int

In [12]:
str(b.dtype)

'float16'

In [38]:
import seera_cuda

In [ ]:
seera_cuda.cuda_mallo

In [37]:
from cuTen import cuten

na = np.arange(0,1024,dtype=np.float16)
nb = np.arange(0,1024,dtype=np.float16)

a = cuten(na)
b = cuten(nb)


AttributeError: module 'seera_cuda' has no attribute 'cuda_malloc_f32'

In [ ]:
        # self.alloc_dtype = {
        #     "float32":seera_cuda.cuda_malloc_f32,
        #     "float16":seera_cuda.cuda_malloc_f16,
        #     "int32":seera_cuda.cuda_malloc_i32,
        #     "int16":seera_cuda.cuda_malloc_i16
        # }