In [1]:
from cuTen import cuten
import numpy as np
 
na = np.arange(0,4*2*3*3,dtype = np.float32).reshape(4,2,3,3)
nb = np.arange(0,4*1*3*3,dtype = np.float32).reshape(4,1,3,3)


a = cuten(na,dtype="float32")
b = cuten(nb,dtype = "float32")


the dtype is float32
the dtype is float32


In [2]:
c = a.concatenate1D(b)

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [3]:
c.shape


(1, 13)

In [13]:
a

[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]


 [[[18. 19. 20.]
   [21. 22. 23.]
   [24. 25. 26.]]

  [[27. 28. 29.]
   [30. 31. 32.]
   [33. 34. 35.]]]


 [[[36. 37. 38.]
   [39. 40. 41.]
   [42. 43. 44.]]

  [[45. 46. 47.]
   [48. 49. 50.]
   [51. 52. 53.]]]


 [[[54. 55. 56.]
   [57. 58. 59.]
   [60. 61. 62.]]

  [[63. 64. 65.]
   [66. 67. 68.]
   [69. 70. 71.]]]]


IT DOES WORK

In [14]:
b

[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]]


 [[[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]


 [[[18. 19. 20.]
   [21. 22. 23.]
   [24. 25. 26.]]]


 [[[27. 28. 29.]
   [30. 31. 32.]
   [33. 34. 35.]]]]


IT DOES WORK

In [3]:
c

[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]

  [[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]]


 [[[18. 19. 20.]
   [21. 22. 23.]
   [24. 25. 26.]]

  [[27. 28. 29.]
   [30. 31. 32.]
   [33. 34. 35.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]


 [[[36. 37. 38.]
   [39. 40. 41.]
   [42. 43. 44.]]

  [[45. 46. 47.]
   [48. 49. 50.]
   [51. 52. 53.]]

  [[18. 19. 20.]
   [21. 22. 23.]
   [24. 25. 26.]]]


 [[[54. 55. 56.]
   [57. 58. 59.]
   [60. 61. 62.]]

  [[63. 64. 65.]
   [66. 67. 68.]
   [69. 70. 71.]]

  [[27. 28. 29.]
   [30. 31. 32.]
   [33. 34. 35.]]]]


IT DOES WORK

In [20]:
tu = (1,2,3,3,10)
yu =1 ;
for gg in tu:
    yu*=gg

In [6]:
one_demo = cuten.ones((5,5))
one_demo.reshape((1,25))
one_demo

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1.]]


IT DOES WORK

In [21]:
h = tuple(tu)
h[3]

3

In [9]:
(a**2) - b



the dtype is float32
[[0.000000e+00 0.000000e+00 2.000000e+00 ... 8.120000e+02 8.700000e+02
  9.300000e+02]
 [9.920000e+02 1.056000e+03 1.122000e+03 ... 3.660000e+03 3.782000e+03
  3.906000e+03]
 [4.032000e+03 4.160000e+03 4.290000e+03 ... 8.556000e+03 8.742000e+03
  8.930000e+03]
 ...
 [8.602560e+05 8.621120e+05 8.639700e+05 ... 9.148920e+05 9.168060e+05
  9.187220e+05]
 [9.206400e+05 9.225600e+05 9.244820e+05 ... 9.771320e+05 9.791100e+05
  9.810900e+05]
 [9.830720e+05 9.850560e+05 9.870420e+05 ... 1.041420e+06 1.043462e+06
  1.045506e+06]]


IT DOES WORK

In [6]:
a.dtype

'float32'

In [4]:
at = (1,2,6,7)
bt = (1,2,6,7)

In [6]:
at == bt

True

In [5]:
c = a+b

the dtype is float32


In [4]:
c

[0.00000e+00 2.00000e+00 4.00000e+00 ... 2.04794e+05 2.04796e+05
 2.04798e+05]


IT DOES WORK